### ISSUE TITLE
Add unit tests and doctests for integrators.py

### ISSUE THREAD

**Issue by icweaver** [cs207-SpaceJam/cs207-FinalProject#33]

**Comment by jmybhm** [comment]
To test_integrators. py, I think the only other unit test to add is when i > i_tol and the system exits with msg ""\nSorry, spacejam did not converge for..."

**Comment by icweaver** [comment]
511bc5887f5d3d4ee75d3adeb320e3e4a2964891 looks good! 

Dealing with `i_tol` next sounds good to me.

**Comment by icweaver** [comment]
Not sure why `.coverage` is still showing up though...
